---
services:
  mediamtx:
    # Latest MTX has bug causing disconnects in vrchat, used 1.14.0 until its fixed
    image: bluenviron/mediamtx:1.14.0-ffmpeg 
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554" # RTSP
      #- "1935:1935" # RTMP
      #- "8888:8888" # HLS
      #- "8889:8889" # WebRTC
      #- "8890:8890" # SRT
    environment:
      MTX_PROTOCOLS: tcp
      #MTX_WEBRTCADDITIONALHOSTS: mtx.yourdomain.tld # most likely not needed
      MTX_HLSALWAYSREMUX: yes
      MTX_HLSVARIANT: mpegts # do not change this for maximum compatibility
      MTX_HLSSEGMENTCOUNT: 7
      MTX_HLSSEGMENTDURATION: 1s
    networks:
      - firefox-network

  firefox:
    image: dentechs/firefox:ffmpeg
    container_name: firefox
    depends_on:
      - mediamtx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=admin
      - PASSWORD=admin
      # Make sure to change FFmpeg pipeline video_size, -framerate, keyint (cpu only), and -g (nvenc only) to match settings here or capture will fail
      - SELKIES_IS_MANUAL_RESOLUTION_MODE=True
      - SELKIES_MANUAL_WIDTH=1920
      - SELKIES_MANUAL_HEIGHT=1080
      - SELKIES_FRAMERATE=30
      - SELKIES_SECOND_SCREEN=False
      - SELKIES_USE_BROWSER_CURSORS=True
      # - FIREFOX_CLI=https://www.linuxserver.io/ #optional
      # FFmpeg pipeline for RTSP streaming to MediaMTX - NVENC hardware acceleration
      - FFMPEG_PIPELINE=ffmpeg -loglevel error -f pulse -i default -f x11grab -video_size 1920x1080 -framerate 30 -i :1.0 -c:v h264_nvenc -preset p3 -tune ll -zerolatency 1 -spatial-aq 1 -temporal-aq 1 -rc cbr -b:v 5000k -maxrate 5000k -bufsize 5000k -g 30 -bf 0 -c:a aac -b:a 192k -ar 48000 -use_wallclock_as_timestamps 1 -af aresample=async=1:first_pts=0 -f rtsp -rtsp_transport tcp -tcp_nodelay 1 rtsp://mediamtx:8554/stream
      # FFmpeg pipeline for RTSP streaming to MediaMTX - CPU Encoding
      # - FFMPEG_PIPELINE=ffmpeg -loglevel error -f pulse -i default -f x11grab -video_size 1920x1080 -framerate 30 -i :1.0 -c:v libx264 -preset veryfast -tune zerolatency -x264-params "rc=cbr:bitrate=5000:vbv-maxrate=5000:vbv-bufsize=5000:keyint=30:bframes=0:sliced-threads=0:aq-mode=2" -c:a aac -b:a 192k -ar 48000 -use_wallclock_as_timestamps 1 -af aresample=async=1:first_pts=0 -f rtsp -rtsp_transport tcp -tcp_nodelay 1 rtsp://mediamtx:8554/stream
    volumes:
      - ./config:/config
    ports:
      - "3100:3000"
      - "3101:3001"
    shm_size: "1gb"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [compute,video,graphics,utility]
    networks:
      - firefox-network

networks:
  firefox-network:
    driver: bridge
