---
services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554" # RTSP
    environment:
      MTX_PROTOCOLS: tcp
    networks:
      - firefox-network

  firefox:
    image: dentechs/firefox:ffmpeg
    container_name: firefox
    depends_on:
      - mediamtx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SELKIES_IS_MANUAL_RESOLUTION_MODE=True
      - SELKIES_MANUAL_WIDTH=1920
      - SELKIES_MANUAL_HEIGHT=1080
      - SELKIES_FRAMERATE=30
      - SELKIES_SECOND_SCREEN=False
      - SELKIES_USE_BROWSER_CURSORS=True
      # - FIREFOX_CLI=https://www.linuxserver.io/ #optional
      # FFmpeg pipeline for RTSP streaming to MediaMTX - NVENC hardware acceleration with zero latency
      - FFMPEG_PIPELINE=ffmpeg -loglevel error -f x11grab -video_size 1920x1080 -framerate 30 -i :1.0 -f pulse -i default -c:v h264_nvenc -preset 3 -zerolatency 1 -rc cbr -b:v 5000k -bufsize 5000k -slices 1 -spatial-aq 1 -temporal-aq 1 -g 30 -c:a aac -b:a 320k -f rtsp rtsp://mediamtx:8554/stream
      # CPU fallback pipeline (x264) with zero latency - commented out  
      # - FFMPEG_PIPELINE=ffmpeg -loglevel error -f x11grab -video_size 1920x1080 -framerate 30 -i :1.0 -f pulse -i default -c:v libx264 -preset veryfast -tune zerolatency -b:v 5000k -slices 1 -aq-mode 2 -c:a aac -b:a 320k -f rtsp rtsp://mediamtx:8554/stream
    volumes:
      - ./config:/config
    ports:
      - "3100:3000"
      - "3101:3001"
    shm_size: "1gb"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [compute,video,graphics,utility]
    networks:
      - firefox-network

networks:
  firefox-network:
    driver: bridge
